# https://github.com/louislam/uptime-kuma

version: '3.8'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - uptime-kuma:/app/data
    ports:
      - "3002:3001"
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000

volumes:
  uptime-kuma:
